### GET request to example server
GET http://localhost:8080/test
###

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name": "Davidson",
  "email": "deh@email.com",
  "password": "1234567"
}
###

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "deh@email.com",
    "password": "1234567"
}
###

###
GET http://localhost:8080/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInN1YiI6ImRlaEBlbWFpbC5jb20iLCJleHAiOjE3NzA1OTU4MDUsImlhdCI6MTc3MDU5NDkwNX0.OafRkK62RlkEPeu6xov7BeJo1H3jCjgL3q3GCa81nvk
###